### ISSUE TITLE
testground/infra: create a nightly job for arabica test

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/test-infra#173]
What we need to do: 
---

Important Job
- [x] Clones the repositories `testground` & `test-infra` 
- [x] Setup & Configure TestGround in the GA
- [x]  GA that takes the latest commit hash of node and builds a new go.mod
- ~[ ]  Granting our job rights in AWS to execute the test~
   -  *We don't need to grant AWS permissions to the GA to execute the test*
- [x]  Schedules a testground test run via composition
- [x]  If the daemon accepts the job run -> we can mark the job as success

Another Job
- [ ] Test Status should be done as a separate job
- [ ] As the daemon exposes it REST endpoint, we can simply curl it to get the latest job run status

## Caveats

Installing testground is required to get the client up and running the test 
This is a bummer as GA is notoriously famous to not have a beefy instance

Hence, we can delegate the calling to another instance that never deletes the client of testground

### Nice to have
- [ ]  we need an slack alert to know what happened to the nightly run

#### Very nice to have
- [ ]  slack alert should contain a link to the dashboard with logs
- [ ] i.e. a simple LogQL query might be nice for the start

**Comment by Bidon15** [comment]
@Bidon15 and @jrmanes to get back to this once robusta nightly is achieved

**Comment by jrmanes** [comment]
hey @Bidon15 

I'm working on this one, I'll let you know as soon as I have something 👌  

cheers!

**Comment by jrmanes** [comment]
Hello!

we can schedule tests using the GitHub Action to TestGround 🚀 

*(In the image we can see an error, no worries for that, it was because I manually killed it, we are running huge tests atm and I didn't want to bother them)*

![Screenshot 2023-04-27 at 09 47 58](https://user-images.githubusercontent.com/32740567/234795501-e1ca2568-5d4c-4846-b3b7-2eab18fa4004.png)

 
The Github Action results looks like this:
![Screenshot 2023-04-27 at 09 49 09](https://user-images.githubusercontent.com/32740567/234795600-0f06a769-5056-48c4-8b4d-c3c2a7732b0c.png)

Execution: [link](https://github.com/jrmanes/.github/actions/runs/4817247095/jobs/8577722146)
As you can see, the last message:
```bash
TestGround ID is: [ch52ejh26un2ddne0640]
```
This gives us information about if we could queue the task or not, if not, we fail the job and returns an `exit 1` code, setting the execution as failed.


I'll do couple of more test

**Comment by Bidon15** [comment]
Closing as barely sufficient
We will open a new one once more feedback comes in
